services:
  postgres:
    image: postgres:18@sha256:74935e72241653ca55e0414067e6d8763aceb8a810eb51b452253ec3dcfc4336
    ports:
      - '5490:5432'
    environment:
      POSTGRES_USER: hermit
      POSTGRES_PASSWORD: hermit
      POSTGRES_DB: hermit
    volumes:
      - hermit-pgdata:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hermit']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  hermit-pgdata:
